### ISSUE TITLE
Might be working but no access to the admin UI

### ISSUE THREAD

**Issue by oleole39** [YunoHost-Apps/watchdog_ynh#2]
Hello,

I wanted to try that app to see whether it could automatically restart some services (I have one which keeps failing after a given server's uptime).

However I don't have access to the admin panel (or maybe there is no admin panel?): the page https://mydomain.tld/yunohost/admin/#/apps/watchdog does not load and the browser's console displays `TypeError: a is undefined` from core-{suffix}.js

At install (YNH 11.2.10 on a VPS with amd64 arch), the installation completes but there is one warning flag: 
```
DEBUG - Setting up watchdog (5.16-1+b1) ...
DEBUG - update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
DEBUG - Created symlink /etc/systemd/system/default.target.wants/watchdog.service -> /lib/systemd/system/watchdog.service.
WARNING - wd_keepalive.service is a disabled or a static unit, not starting it.
```
EDIT: running `sudo apt install watchdog` manually on my system shows the same messages.

As for the service watchdog.service, it is active and running.

**Comment by OniriCorpe** [comment]
As far as i know, there is no webpage associated with this software

And it is used to reboot the server in case of freeze, not restart the server’s services 

I doubt your VPS can support this app, since it requires a special hardware to function properly

**Comment by oleole39** [comment]
Thanks. good points, this app is not for me.

Still a bit strange though that the admin panel for this app appears as an everloading empty template page. Given that the admin UI page is partially generated from the app manifest, there should be the minimum app info provided in there (I can see in the Browser's Dev Tools that the JS objects are correctly retrieved). Not sure why it doesn't display though. For instance it makes the app not removable from the webUI (although it can be removed from the SSH terminal).  But maybe it is only for me due to the imperfect install.
